version: '3'
services:
  db:
    image: mysql
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3002:3002"
    depends_on:
      - db
    tty: true
    stdin_open: true