default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: flat_plat_api_2_development

test:
  <<: *default
  database: flat_plat_api_2_test

production:
  <<: *default
  database: flat_plat_api_2_production
  username: flat_plat_api_2
  password: <%= ENV['FLAT_PLAT_API_2_DATABASE_PASSWORD'] %>
